DBHost = "localhost"
DBPort = "5432"
DBUser = "postgres"
DBPassword = "VingB2by"
DBName = "blog"
DBDriver = "postgres"

#Redis
RedisHost = "127.0.0.1"
RedisPort = "6379"
RedisPwd = ""
RedisDB = 0
#服务器地址
serverHost="https://vingdream.cn"
serverPort="443"

#支持的文件后缀
suffixes = [
    "jpg",
    "png",
    "jpeg",
    "mp3",
    "wav",
    "aac",
    "flac",
    "avi",
    "mov",
    "mp4",
    "wmv",
    "rmvb",
    "mkv",
    "flv"
]

#最大上传文件大小,单位M
MaxFileSize = 500

#文件下载的域名
FileDownloadHost="/static/"

FileDownloadPrefix="/files"

#日志缓冲区
LoggerBuffer=1000

#日志缓冲区等候时间(秒)
LoggerBufDuration=5

#签名相关
SignKey="cst_noc"
SignSwitch=false

#会话相关
SessionKey="VingB2by"
MaxLifeTime=21600
Path="/"
HTTPOnly=true
MaxAge=432000
